// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjBcJYpsTkzdaKQEmY0s4jQUma4AypQX0',
    appId: '1:1005810087329:web:96d6fd2e35f6884ff647e0',
    messagingSenderId: '1005810087329',
    projectId: 'nurserycare-ed521',
    authDomain: 'nurserycare-ed521.firebaseapp.com',
    storageBucket: 'nurserycare-ed521.appspot.com',
    measurementId: 'G-RHE1BVR6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrQEdOkcAdPggywnf29sa8evAVebWRwE',
    appId: '1:1005810087329:android:184d9e541542ca60f647e0',
    messagingSenderId: '1005810087329',
    projectId: 'nurserycare-ed521',
    storageBucket: 'nurserycare-ed521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNedRJN9tm1eC7TR861rZ-oQ9jwV4fgqE',
    appId: '1:1005810087329:ios:e66b0e840007200bf647e0',
    messagingSenderId: '1005810087329',
    projectId: 'nurserycare-ed521',
    storageBucket: 'nurserycare-ed521.appspot.com',
    iosBundleId: 'com.example.nurserycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNedRJN9tm1eC7TR861rZ-oQ9jwV4fgqE',
    appId: '1:1005810087329:ios:c45fc22bde522bfaf647e0',
    messagingSenderId: '1005810087329',
    projectId: 'nurserycare-ed521',
    storageBucket: 'nurserycare-ed521.appspot.com',
    iosBundleId: 'com.example.nurserycare.RunnerTests',
  );
}
